# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 18:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160129_0006'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subject',
            managers=[
                ('subjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
