# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160205_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='per_addr',
            field=models.CharField(choices=[(b'Addr1', b'Address 1'), (b'Addr2', b'Address 2'), (b'Addr3', b'Address 3'), (b'Addr4', b'Address 4'), (b'Addr5', b'Address 5'), (b'Addr6', b'Address 6'), (b'Addr7', b'Address 7')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='per_addr',
            field=models.CharField(choices=[(b'Addr1', b'Address 1'), (b'Addr2', b'Address 2'), (b'Addr3', b'Address 3'), (b'Addr4', b'Address 4'), (b'Addr5', b'Address 5'), (b'Addr6', b'Address 6'), (b'Addr7', b'Address 7')], max_length=200),
        ),
    ]
