# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160210_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.FileField(default=b'', upload_to=students.models.get_upload_file_name),
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.FileField(default=b'', upload_to=students.models.get_upload_file_name),
        ),
    ]
